cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'minicom'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

brew 'pyenv'
brew 'pyenv-virtualenv'

# cask 'firefox'
cask 'google-chrome'
# cask 'handbrake'
cask 'macdown'
# cask 'mactex'
cask 'slack'
cask 'sublime-text'
cask 'transmission'
cask 'tunnelbear'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vlc'

